### ISSUE TITLE
Services Folder missing from Unity 4.17.1

### ISSUE THREAD

**Issue by ibytergj** [magnopus-opensource/connected-spaces-platform#286]
**Describe the bug**

When I updated to the latest Unity core version 4.17.1 the services folder disappeared from the code under packages.
I also get two errors now in one of thw sample cs files

Assets\Scripts\HelloWorld.cs(290,44): error CS0234: The type or namespace name 'Services' does not exist in the namespace 'Csp' (are you missing an assembly reference?)

Assets\Scripts\HelloWorld.cs(324,44): error CS0234: The type or namespace name 'Services' does not exist in the namespace 'Csp' (are you missing an assembly reference?)

**To Reproduce**

1. In a project where you have the Multiplayer sample setup update the package to 4.17.1 and see if you have this issue.

**Expected behaviour**

No errors in console

**Screenshots**

![image](https://github.com/magnopus-opensource/connected-spaces-platform/assets/52046406/560d46fa-6f89-42bb-aa42-719a7fc74166)

**CSP version (please complete the following information):**

4.17.1

**Language:**

Either C++, C#, JavaScript or TypeScript
C# Unity

**Comment by MAG-SamBirley** [comment]
We've now [updated](https://github.com/magnopus-opensource/connected-spaces-platform/pull/293) the Unity CSP examples to 4.17.1. Please do reach out if you have any further issues.
