### ISSUE TITLE
Clang compiler complains about initialization order in CSP 5.2.0+536 on M1 mac

### ISSUE THREAD

**Issue by kevinmagnopus** [magnopus-opensource/connected-spaces-platform#506]
**Describe the bug**

When building an application that uses CSP 5.2.0, the following compiler warning is issued:

In file included from ./include/CSP/Systems/Settings/SettingsSystem.h:21:
./include/CSP/Systems/Settings/SettingsCollection.h:105:5: warning: field 'Type' will be initialized after base 'csp::systems::ResultBase' [-Wreorder-ctor]
                : Type(AvatarType::None), csp::systems::ResultBase(ResCode, HttpResCode) {};
                  ^~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  csp::systems::ResultBase(ResCode, HttpResCode) Type(AvatarType::None)
1 warning generated.

**To Reproduce**

1. Create an application that uses the CSP libraries
2. Build the application on an Apple Silicon Mac
3. Notice the warning

**Expected behaviour**

No warning is emitted when building a CSP application

**CSP version (please complete the following information):**

5.2.0+536

**Language:**

C++

**Desktop (please complete the following information):**

OSX on Apple Silicon

**Comment by MAG-SamBirley** [comment]
Thanks @kevinmagnopus - we'll likely get this fixed in the next couple weeks.

**Comment by MAG-SamBirley** [comment]
Fixed in #550. Thanks for reporting this!
